<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>云龙&#39;s Blog </title>
    <link>http://replace-this-with-your-hugo-site.com/post/</link>
    <language>en-us</language>
    <author>Shekhar Gulati</author>
    <rights>(C) 2016</rights>
    <updated>2016-03-19 22:08:03 &#43;0800 CST</updated>

    
      
        <item>
          <title>promise in detail</title>
          <link>http://replace-this-with-your-hugo-site.com/post/promise-in-detail/</link>
          <pubDate>Sat, 19 Mar 2016 22:08:03 CST</pubDate>
          <author>Shekhar Gulati</author>
          <guid>http://replace-this-with-your-hugo-site.com/post/promise-in-detail/</guid>
          <description>

&lt;h1 id=&#34;javascript-promises-in-wicked-detail:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;Javascript Promises &amp;hellip; In Wicked Detail&lt;/h1&gt;

&lt;p&gt;&lt;a href=&#34;http://dailyjs.com/2014/02/20/promises-in-detail/&#34;&gt;原文地址&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;我现在已经一直在 Javascript 使用 Promises 一段时间了。 它们一开始使用起来可能会有点脑袋绕不过来的感觉。 我现在能非常高效地使用 Promises， 但是实际上我并不能完全理解它们是怎么样工作的。 这篇文章就是我对他们的解析。 如果你能坚持到最后，你也一样能够明白 Promises 的工作方式。&lt;/p&gt;

&lt;p&gt;我们将会逐步地实现一样 Promise 满足 &lt;a href=&#34;https://promisesaplus.com/&#34;&gt;Promise/A+ spec&lt;/a&gt; 的大部分要求，并且弄明白 promises 是如何满足异步编程的要求的。 这篇文章假定你已经对 Promises 比较熟悉了。 如果你不熟悉，那么可以去 promisejs.org 去看看。&lt;/p&gt;

&lt;h2 id=&#34;why:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;Why?&lt;/h2&gt;

&lt;p&gt;为什么需要这么麻烦去了解 Promises 的实现细节到这个地步呢？ 真正的了解一样东西是怎么样工作能够使你更有效的使用他，并且在发生问题时能够更有效的调试问题。 我是因为我和一个同事在一个奇怪的 Promise 情景下被难住了才有了写这篇文章的想法。 如果当时我知道了我现在所知道，那么我们就不会被难住了。&lt;/p&gt;

&lt;h2 id=&#34;the-simplest-use-case:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;The Simplest Use Case&lt;/h2&gt;

&lt;p&gt;让我们从实现一个最简单的 Promise 开始。 我们想从如下的使用方式：&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
doSomething(function(value) {  
  console.log(&#39;Got a value:&#39; value);
});

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;变成如下的：&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
doSomething().then(function(value) {  
  console.log(&#39;Got a value:&#39; value);
});

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;为了做到这一点，我们只需改变一下 &lt;code&gt;doSomething()&lt;/code&gt;，从：&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
function doSomething(callback) {  
  var value = 42;
  callback(value);
}

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;变成这个 &lt;code&gt;&amp;quot;Promise&amp;quot;&lt;/code&gt; 的最基本的解决方法：&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
function doSomething() {  
  return {
    then: function(callback) {
      var value = 42;
      callback(value);
    }
  };
}

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;当然这只是回调模式的一个小小的语法糖，目前为止也是非常没有意义的语法糖。 但是这也是一个起点，我们已经开始无意中发现了在 Promises 后面的核心思想：&lt;/p&gt;

&lt;blockquote&gt;
&lt;p&gt;Promises 将一个最终值的概念（符号）放进了一个对象中。&lt;/p&gt;

&lt;p&gt;Promises capture the notion of an eventual value into an object.&lt;/p&gt;
&lt;/blockquote&gt;

&lt;p&gt;这就是 Promises 为什么这么有意思的主要原因。 一旦最终值的概念像这样被获取，我们就可以开始构建一些强大的东西了。我们稍后就会展开探索。&lt;/p&gt;

&lt;h2 id=&#34;defining-the-promise-type:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;Defining the Promise Type&lt;/h2&gt;

&lt;p&gt;一个简单的对象字面值并不能支撑 Promise。 我们将定义一个实际的 &lt;code&gt;Promise&lt;/code&gt; 类型，然后在这基础上持续的扩展。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
function Promise(fn) {  
  var callback = null;
  this.then = function(cb) {
    callback = cb;
  };

  function resolve(value) {
    callback(value);
  }

  fn(resolve);
}

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;并且重新实现 &lt;code&gt;doSomething()&lt;/code&gt; 来使用这个 Promise&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
function doSomething() {  
  return new Promise(function(resolve) {
    var value = 42;
    resolve(value);
  });
}

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;这里有一个问题。 如果你追踪执行过程，你就会发现 &lt;code&gt;resolve()&lt;/code&gt; 在 &lt;code&gt;then()&lt;/code&gt; 之前执行的话， &lt;code&gt;callback&lt;/code&gt; 就是 &lt;code&gt;null&lt;/code&gt; 的。 我们使用 &lt;code&gt;setTimeout&lt;/code&gt; 来屏蔽这个问题。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
function Promise(fn) {  
  var callback = null;
  this.then = function(cb) {
    callback = cb;
  };

  function resolve(value) {
    // force callback to be called in the next
    // iteration of the event loop, giving
    // callback a chance to be set by then()
    setTimeout(function() {
      callback(value);
    }, 1);
  }

  fn(resolve);
}

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;使用了适当的 hack 手段， 这段代码已经可以工作了， 一定程度上。。。。&lt;/p&gt;

&lt;h2 id=&#34;thie-code-is-brittle-and-bad:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;Thie Code is Brittle and Bad&lt;/h2&gt;

&lt;p&gt;我们这个天真的、简单的 Promise 实现方式必须使用一个异步方式才能工作。 非常容易就能够让它再次运行失败，只要异步地调用 &lt;code&gt;then()&lt;/code&gt; 我们就能够立马回到 &lt;code&gt;callback&lt;/code&gt; 变成 &lt;code&gt;null&lt;/code&gt; 的情况。 为什么我要陷害你让你这么快就失败呢？ 因为上面的实现方式能够让你相当容易的理解。 &lt;code&gt;then()&lt;/code&gt; 和 &lt;code&gt;resolve&lt;/code&gt; 不会远离。 他们是 Promises 的核心概念。&lt;/p&gt;

&lt;h2 id=&#34;promises-have-state:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;Promises have State&lt;/h2&gt;

&lt;p&gt;我们上面实现的脆弱的代码暴露了一些问题。 Promises 是有状态的。 我们在处理前需要知道他们正处于一个什么状态，并且要保证我们正确的实现状态的迁移。 以此来除去代码的脆弱性。&lt;/p&gt;

&lt;ul&gt;
&lt;li&gt;一个 Promise 可以处于 &lt;code&gt;pending&lt;/code&gt; 状态，等待一个新值；或者处于 &lt;code&gt;resolved&lt;/code&gt; 状态，已经保有一个值。&lt;/li&gt;
&lt;li&gt;一旦一个 Promise 解析成了一个值(resolve to a value)， 那么它将保留这个值不会再发生变化。&lt;/li&gt;
&lt;/ul&gt;

&lt;p&gt;一个 Promise 也可以被拒绝，但是我们会在下一步再来做错误处理。&lt;/p&gt;

&lt;p&gt;在我们的实现中显式的记录状态，这样我们就可以去掉我们之前的 hack 了。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
function Promise(fn) {  
  var state = &#39;pending&#39;;
  var value;
  var deferred;

  function resolve(newValue) {
    value = newValue;
    state = &#39;resolved&#39;;

    if(deferred) {
      handle(deferred);
    }
  }

  function handle(onResolved) {
    if(state === &#39;pending&#39;) {
      deferred = onResolved;
      return;
    }

    onResolved(value);
  }

  this.then = function(onResolved) {
    handle(onResolved);
  };

  fn(resolve);
}

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;这变得更复杂了，但是现在调用者可以随时调用 &lt;code&gt;then()&lt;/code&gt; 方法和 &lt;code&gt;resolve&lt;/code&gt; 方法了。 它可以在异步与同步的代码中正确工作。&lt;/p&gt;

&lt;p&gt;这是因为 &lt;code&gt;state&lt;/code&gt; 状态标记。 &lt;code&gt;then()&lt;/code&gt; 和 &lt;code&gt;resolve()&lt;/code&gt; 都切换到了新的方法 &lt;code&gt;handle()&lt;/code&gt; 来工作， 这个方法会根据状态来决定做两件事的其中一件：&lt;/p&gt;

&lt;ul&gt;
&lt;li&gt;&lt;p&gt;当调用者在调用 &lt;code&gt;resolve()&lt;/code&gt; 之前先调用 &lt;code&gt;then()&lt;/code&gt; 方法，这就意味着没有一个已经准备好的值来供回调函数使用。 这种情形状态为 &lt;code&gt;pending&lt;/code&gt;，我们先把回调函数保存起来后面使用。 稍后在调用 &lt;code&gt;resolve()&lt;/code&gt; 时，我们可以调用这个回调函数，并将值传给这个回调函数。&lt;/p&gt;&lt;/li&gt;

&lt;li&gt;&lt;p&gt;如果调用 &lt;code&gt;resolve()&lt;/code&gt; 先于 &lt;code&gt;then()&lt;/code&gt;： 这个情形下我们先保存我们的值。 一旦 &lt;code&gt;then()&lt;/code&gt; 被调用，我们就可以使用这个值。&lt;/p&gt;&lt;/li&gt;
&lt;/ul&gt;

&lt;p&gt;注意到 &lt;code&gt;setTimeout&lt;/code&gt; 已经不见了。 这只是暂时的，它会回来的。 但是咱一件一件事来。&lt;/p&gt;

&lt;p&gt;利用这个 Promise ，我们调用它们的顺序已经没关系了。 我们可以根据我们的需要随时调用 &lt;code&gt;then()&lt;/code&gt; 和 &lt;code&gt;resolve&lt;/code&gt;。 这也是将最终结果的符号放到一个对象中的其中一个强大的地方。&lt;/p&gt;

&lt;p&gt;我们依然有相当多的规范需要实现，但是我们的 Promises 已经非常有用的。 这个实现允许我们重复调用 &lt;code&gt;then()&lt;/code&gt;方法，我们总能够得到相同的值。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
var promise = doSomething();

promise.then(function(value) {  
  console.log(&#39;Got a value:&#39;, value);
});

promise.then(function(value) {  
  console.log(&#39;Got the same value again:&#39;, value);
});

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;使用我们目前为止对 Promise 的实现的话上述的代码不一样完全正确。 如果相反的顺序发生，比如先多次调用 &lt;code&gt;then()&lt;/code&gt; 方法然后再调用 &lt;code&gt;resolve&lt;/code&gt; 方法，只有最后一个 &lt;code&gt;then()&lt;/code&gt; 方法的回调函数会被执行。 修补这个bug的方法是保存一个需要延后执行的回调函数的列表。 为了保持代码简单易懂，我决定不这么做了，现在的代码已经够长了。&lt;/p&gt;

&lt;h2 id=&#34;chaining-promises:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;Chaining Promises&lt;/h2&gt;

&lt;p&gt;因为 Promises 会捕获异步性的符号到一个对象中（Since Promises capture the notion of asynchronicity in an object, 不知道怎么翻译- -），所以我们能够把他们串联起来，映射，将他们并行或者顺序执行等各种有用的事情。 像下面的代码在 Promises 中是非常常见的。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
getSomeData()  
.then(filterTheData)
.then(processTheData)
.then(displayTheData);

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;&lt;code&gt;getSomeData&lt;/code&gt; 返回的是一个 Promise，证据是它也调用了一个 &lt;code&gt;then()&lt;/code&gt; 方法，但是第一个 then 的结果也是一个 Promise ，因为我们又调用了一次 &lt;code&gt;then()&lt;/code&gt;（并且又再后面调用了一次!）。 这就是确确实实发生的，如果我们能够确认 &lt;code&gt;then()&lt;/code&gt; 返回一个 Promise， 事情将会变得有趣起来。&lt;/p&gt;

&lt;blockquote&gt;
&lt;p&gt;&lt;code&gt;then()&lt;/code&gt; 总是返回一个 Promise&lt;/p&gt;
&lt;/blockquote&gt;

&lt;p&gt;这里是我们添加了链式处理后的 Promise 类型&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
function Promise(fn) {  
  var state = &#39;pending&#39;;
  var value;
  var deferred = null;

  function resolve(newValue) {
    value = newValue;
    state = &#39;resolved&#39;;

    if(deferred) {
      handle(deferred);
    }
  }

  function handle(handler) {
    if(state === &#39;pending&#39;) {
      deferred = handler;
      return;
    }

    if(!handler.onResolved) {
      handler.resolve(value);
      return;
    }

    var ret = handler.onResolved(value);
    handler.resolve(ret);
  }

  this.then = function(onResolved) {
    return new Promise(function(resolve) {
      handle({
        onResolved: onResolved,
        resolve: resolve
      });
    });
  };

  fn(resolve);
}

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;呼呼， 它已经变得有点古怪了。 你不是在庆幸我们可以慢慢地构建它吗？ 这里真正的关键在于 &lt;code&gt;then()&lt;/code&gt; 返回一个新的 Promise。&lt;/p&gt;

&lt;p&gt;因为 &lt;code&gt;then()&lt;/code&gt; 总是返回一个新的 Promise 对象， 那么总会至少有一个 Promise 被创建， 被 resolved ， 然后被忽略。 这看起来有点浪费。 回调的方式并没有这种问题。 这是一种反对 Promises 的理由。 你会开始发现为什么有些 Javascript 社区会回避使用 Promises 了。&lt;/p&gt;

&lt;p&gt;这第二个 Promise 会 resolve 到一个什么的值呢？ 它会接受第一个 Promise 的返回值。 这个发生在 &lt;code&gt;handle()&lt;/code&gt; 的底部， &lt;code&gt;handler&lt;/code&gt; 对象的持有 &lt;code&gt;onResolved&lt;/code&gt; 回调函数 和 &lt;code&gt;resolve()&lt;/code&gt; 函数的引用（注： 这个 resolve 是新的 Promise 内部的 resolve 函数， 而不是原来的 Promise 的）。 上面有不止一份 &lt;code&gt;resolve()&lt;/code&gt; 函数的拷贝在传来传去， 每个 Promise 都会得到一个属于它们自己的拷贝， 并通过闭包传递的方式来使用。 这是第一个 Promise 与第二个 Promise 之间的桥梁。 我们在这一行总结第一个 Promise：&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
var ret = handler.onResolved(value);  

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;在这个例子中，&lt;code&gt;handler.onResolved&lt;/code&gt; 是&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
function(value) {  
  console.log(&amp;quot;Got a value:&amp;quot;, value);
}

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;换句话来说，就是我们传到第一个 &lt;code&gt;then()&lt;/code&gt; 的参数。 其返回值将作为 resolve 第二个 Promise 的值。 这样链式调用就完成了。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
doSomething().then(function(result) {  
  console.log(&#39;first result&#39;, result);
  return 88;
}).then(function(secondResult) {
  console.log(&#39;second result&#39;, secondResult);
});

// the output is
//
// first result 42
// second result 88


doSomething().then(function(result) {  
  console.log(&#39;first result&#39;, result);
  // not explicitly returning anything
}).then(function(secondResult) {
  console.log(&#39;second result&#39;, secondResult);
});

// now the output is
//
// first result 42
// second result undefined

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;&lt;code&gt;then()&lt;/code&gt; 总是返回一个新的 Promise ，那么链式调用可以多深都没问题了。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
doSomething().then(function(result) {  
  console.log(&#39;first result&#39;, result);
  return 88;
}).then(function(secondResult) {
  console.log(&#39;second result&#39;, secondResult);
  return 99;
}).then(function(thirdResult) {
  console.log(&#39;third result&#39;, thirdResult);
  return 200;
}).then(function(fourthResult) {
  // on and on...
});

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;在上面的例子中，如果我们想在咀咒得到的结果，该怎么做呢？ 使用链式的话，我们只能手动的构建这个结果。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
doSomething().then(function(result) {  
  var results = [result];
  results.push(88);
  return results;
}).then(function(results) {
  results.push(99);
  return results;
}).then(function(results) {
  console.log(results.join(&#39;, &#39;);
});

// the output is
//
// 42, 88, 99

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;Promise 总是会 resolve 一个值。 如果你需要传递多于单一一个的值，你需要创建一个复合类型的值，如数组，对象等。&lt;/p&gt;

&lt;p&gt;一个可能较好的办法是使用 Promise 库提供的 &lt;code&gt;all()&lt;/code&gt; 方法或者其他有用的工具方法来提升 Promises 的有用性，这个就留给你们自己去发现了。&lt;/p&gt;

&lt;h2 id=&#34;the-callback-is-optional:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;The Callback is Optional&lt;/h2&gt;

&lt;p&gt;&lt;code&gt;then()&lt;/code&gt; 的回调函数不是必须的。 如果你不传递一个回调函数，那么新的 Promise resolve 值将跟上一个 Promise 一样。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
doSomething().then().then(function(result) {  
  console.log(&#39;got a result&#39;, result);
});

// the output is
//
// got a result 42

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;你可以看到在 &lt;code&gt;handle()&lt;/code&gt;里面，如果没有回调函数的话，就直接 resolve 这个 Promise 并退出。 &lt;code&gt;value&lt;/code&gt; 直接使用上一个的值。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
if(!handler.onResolved) {  
  handler.resolve(value);
  return;
}

&lt;/code&gt;&lt;/pre&gt;

&lt;h2 id=&#34;returning-promises-inside-the-chain:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;Returning Promises Inside the Chain&lt;/h2&gt;

&lt;p&gt;我们链式实现的方式有点 naive。 它只是简单的将 resolved 的值往下传递。 那么如果传递的值是一个 Promise呢？ 例如：&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
doSomething().then(result) {  
  // doSomethingElse returns a Promise
  return doSomethingElse(result)
}.then(function(finalResult) {
  console.log(&amp;quot;the final result is&amp;quot;, finalResult);
});

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;正如上面所示，我们不会得到我们想要的结果。 &lt;code&gt;finalResult&lt;/code&gt; 不是一个完全解析过的值，他本身就是一个 Promise。 为了得到想要的值，我们需要这么做：&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
doSomething().then(result) {  
  // doSomethingElse returns a Promise
  return doSomethingElse(result)
}.then(function(anotherPromise) {
  anotherPromise.then(function(finalResult) {
    console.log(&amp;quot;the final result is&amp;quot;, finalResult);
  });
});

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;谁会想这样来糟蹋自己的代码？ 让我们的 Promise 实现无缝地来处理这种情况吧。 很简单就可以， 在&lt;code&gt;resolve&lt;/code&gt;内部，只要添加一个特殊的分支来解析这个 Promise。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
function resolve(newValue) {  
  // 通过 duck-typing 方法判断，如果是一个 promise 的话
  if(newValue &amp;amp;&amp;amp; typeof newValue.then === &#39;function&#39;) {
    newValue.then(resolve);
    return;
  }
  state = &#39;resolved&#39;;
  value = newValue;

  if(deferred) {
    handle(deferred);
  }
}

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;我们会一直递归调用 &lt;code&gt;resolve()&lt;/code&gt; 方法，直到它不是一个 Promise。
（注： 这里的 newValue.then(resolve) 意思是调用这个 Promise 的 then 方法， 将原来的 promise 的 resolve 函数作为回调函数传递给上述 Promise 的 then 方法）&lt;/p&gt;

&lt;p&gt;这可能会造成一个无限的循环。 &lt;code&gt;Promise/A+&lt;/code&gt; 规范中建议在实现中检测这种无限循环，但不是必须的。 另外，我们的实现并不满足要求。 我们也不打算在这篇文章中完全支持规范。 好奇的话，我建议你去看看 &lt;code&gt;Promise resolution procedure&lt;/code&gt;。&lt;/p&gt;

&lt;p&gt;注意到对 &lt;code&gt;newValue&lt;/code&gt; 是否是一个 Promise 的判断是有多松吗？ 我们只是查找了一下有没有 &lt;code&gt;then()&lt;/code&gt; 方法。 这是 duck typing 判定， 它可以允许多种不同的 Promise 实现能够互相调用。 多种不同的 Promise 库混合使用是很常见的，你使用的不同的第三方库可能各自用着自己的不同的 Promise 实现。&lt;/p&gt;

&lt;p&gt;不同的 Promise 实现能够相互操作，只要他们都满足上述的 Promise/A+ 规范。&lt;/p&gt;

&lt;p&gt;适当的使用链式调用，我们的实现已经相当完整了。 但是我们完全把错误处理遗忘了。&lt;/p&gt;

&lt;h2 id=&#34;rejecting-promises:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;Rejecting Promises&lt;/h2&gt;

&lt;p&gt;当在 Promise 期间发生错误时，它需要以某个原因来拒绝（rejected with a reason）。 那么调用者怎么知道这个发生了呢？ 他们可以通过在 &lt;code&gt;then()&lt;/code&gt; 的再传递第二个回调函数来发现。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
doSomething().then(function(value) {  
  console.log(&#39;Success!&#39;, value);
}, function(error) {
  console.log(&#39;Uh oh&#39;, error);
});

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;之前提过， Promise 的状态会从 &lt;code&gt;pending&lt;/code&gt; 迁移到 &lt;code&gt;resolved&lt;/code&gt; 或者 &lt;code&gt;rejected&lt;/code&gt; 状态的其中一种，只能一种。 换句话来说，上面的两个回调函数，只有其中一个会执行。&lt;/p&gt;

&lt;p&gt;Promises 依靠 &lt;code&gt;reject()&lt;/code&gt; 来实现拒绝， &lt;code&gt;resolve&lt;/code&gt; 的邪恶的双胞胎兄弟。 这是添加了错误处理支持后的 &lt;code&gt;doSomething()&lt;/code&gt;：&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
function doSomething() {  
  return new Promise(function(resolve, reject) {
    var result = somehowGetTheValue(); 
    if(result.error) {
      reject(result.error);
    } else {
      resolve(result.value);
    }
  });
}

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;在 Promise 的实现中，我们必须负责处理拒绝的情况。 只要一个 Promise 被拒绝了， 所有在下游的 Promises 都必须被拒绝。&lt;/p&gt;

&lt;p&gt;再看一下一个完整的 Promise 实现，这次添加了错误处理支持&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
function Promise(fn) {  
  var state = &#39;pending&#39;;
  var value;
  var deferred = null;

  function resolve(newValue) {
    if(newValue &amp;amp;&amp;amp; typeof newValue.then === &#39;function&#39;) {
      newValue.then(resolve, reject);
      return;
    }
    state = &#39;resolved&#39;;
    value = newValue;

    if(deferred) {
      handle(deferred);
    }
  }

  function reject(reason) {
    state = &#39;rejected&#39;;
    value = reason;

    if(deferred) {
      handle(deferred);
    }
  }

  function handle(handler) {
    if(state === &#39;pending&#39;) {
      deferred = handler;
      return;
    }

    var handlerCallback;

    if(state === &#39;resolved&#39;) {
      handlerCallback = handler.onResolved;
    } else {
      handlerCallback = handler.onRejected;
    }

    if(!handlerCallback) {
      if(state === &#39;resolved&#39;) {
        handler.resolve(value);
      } else {
        handler.reject(value);
      }

      return;
    }

    var ret = handlerCallback(value);
    handler.resolve(ret);
  }

  this.then = function(onResolved, onRejected) {
    return new Promise(function(resolve, reject) {
      handle({
        onResolved: onResolved,
        onRejected: onRejected,
        resolve: resolve,
        reject: reject
      });
    });
  };

  fn(resolve, reject);
}

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;除了添加了 &lt;code&gt;reject()&lt;/code&gt; 方法，&lt;code&gt;handle()&lt;/code&gt; 里面也需要识别拒绝的情形。 在 &lt;code&gt;handle()&lt;/code&gt; 究竟是执行拒绝的逻辑还是解析的逻辑取决于 &lt;code&gt;state&lt;/code&gt; 的值。 这个 &lt;code&gt;state&lt;/code&gt; 同样也会推送到下一个 Promise 中，因为调用下一个 Promise 的 &lt;code&gt;resolve()&lt;/code&gt; 或 &lt;code&gt;reject()&lt;/code&gt; 会继承上个 Promise 的执行路径。（即上一个 Promise 调用了 reoslve 的话， 下一个也会调用 resolve， 当然错误处理的情况例外。）&lt;/p&gt;

&lt;p&gt;当使用 Promises 的时候，很容易忽略错误的回调函数。 但是如果你这么做，你就会没法知道有哪些东西发生错误了。 至少，你需要在你的链式调用的最后一个 Promise 中添加错误处理的回调函数。 看看下面的章节以获取更多关于隐藏了错误的情形的信息。&lt;/p&gt;

&lt;h2 id=&#34;unexpected-errors-should-also-lead-to-rejection:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;Unexpected Errors Should Also Lead to Rejection&lt;/h2&gt;

&lt;p&gt;目前为止错误处理的逻辑只处理已知的错误。 但是很有可能有意想不到的异常出现，完全毁掉一切。 非常有必要在 Promise 的实现中捕捉这种异常，然后做出相应的拒绝行为。&lt;/p&gt;

&lt;p&gt;这意味着 &lt;code&gt;resolve()&lt;/code&gt; 需要在 &lt;code&gt;try/catch&lt;/code&gt; 块中包裹。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
function resolve(newValue) {  
  try {
    // ... as before
  } catch(e) {
    reject(e);
  }
}

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;保证传递给我们的回调函数不能抛出不被处理的异常非常重要。 这些回调函数在 &lt;code&gt;handle()&lt;/code&gt; 中执行， 所以我们最后需要：&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
function handle(deferred) {  
  // ... as before

  var ret;
  try {
    ret = handlerCallback(value);
  } catch(e) {
    handler.reject(e);
    return;
  }

  handler.resolve(ret);
}

&lt;/code&gt;&lt;/pre&gt;

&lt;h2 id=&#34;promise-can-swallow-errors:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;Promise can Swallow Errors!&lt;/h2&gt;

&lt;p&gt;有可能对 Promise 的误解会导致完全吞掉了一个错误。 这坑了很多人。&lt;/p&gt;

&lt;p&gt;考虑下面的例子：&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
function getSomeJson() {  
  return new Promise(function(resolve, reject) {
    var badJson = &amp;quot;&amp;lt;div&amp;gt;uh oh, this is not JSON at all!&amp;lt;/div&amp;gt;&amp;quot;;
    resolve(badJson);
  });
}

getSomeJson().then(function(json) {  
  var obj = JSON.parse(json);
  console.log(obj);
}, function(error) {
  console.log(&#39;uh oh&#39;, error);
});

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;这里会发生什么呢？ 我们在 &lt;code&gt;then()&lt;/code&gt; 的回调函数期望着合法的 JSON 数据。 所以这个函数会非常 naively 地尝试解析传入的数据， 这会导致异常。但是我们已经有了一个错误处理的回调函数，所以应该没问题，对吧？&lt;/p&gt;

&lt;p&gt;不！ 这个错误回调函数并不会被调用。 如果你执行上面的例子， 你不会得到任何输出。 没有错误， 没有任何东西。 纯粹的冰冷的沉默。&lt;/p&gt;

&lt;p&gt;为什么呢？ 因为这个没有被处理的异常发生在我们的 &lt;code&gt;then()&lt;/code&gt; 的回调函数中，它是在 &lt;code&gt;hanlde()&lt;/code&gt; 中被捕捉。 这个会引起 &lt;code&gt;handle()&lt;/code&gt; reject 这个 Promise，然后 &lt;code&gt;then()&lt;/code&gt; 返回，这时候已经不是我们响应的 Promise 了， 因为这个 Promise 已经正确的 resolved 了。 （其实就是 onResolved 与 onRejected 只有一个会被执行， 同一个 then 中的 onResolved 发生的异常不会导致 onRejected 被调用，需要一下一个 Promise 来处理）。&lt;/p&gt;

&lt;p&gt;请时刻记住，在 &lt;code&gt;then()&lt;/code&gt; 内部的回调函数执行时， 这个响应的 Promise 已经解析过了。 你的回调函数的结果对这个 Promise 没有任何影响。&lt;/p&gt;

&lt;p&gt;如果你相爱那个捕捉到上述的错误，你必须在下游的错误处理的回调函数。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
getSomeJson().then(function(json) {  
  var obj = JSON.parse(json);
  console.log(obj);
}).then(null, function(error) {
  console.log(&amp;quot;an error occured: &amp;quot;, error);
});

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;现在我们就能够正确记录错误了。&lt;/p&gt;

&lt;p&gt;以我的经验看来，这个就是 Promises 的最大的缺陷了。 继续阅读下一节可能提供一个较好的解决方法。&lt;/p&gt;

&lt;h2 id=&#34;done-to-the-rescue:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;done() to the Rescue&lt;/h2&gt;

&lt;p&gt;大多数(但并非全部) Promise 的库都有一个 &lt;code&gt;done()&lt;/code&gt; 方法。 它跟 &lt;code&gt;then()&lt;/code&gt; 非常相似， 除了它能够避免上述 &lt;code&gt;then()&lt;/code&gt; 的缺陷。&lt;/p&gt;

&lt;p&gt;&lt;code&gt;done()&lt;/code&gt; 可以在使用 &lt;code&gt;then()&lt;/code&gt; 的任何地方使用。 最关键的不同点在与它不会返回一个 Promise， 且在 &lt;code&gt;done()&lt;/code&gt; 方法内的任何未处理的异常都不会被 Promise 的实现处理。 换句话说， &lt;code&gt;done()&lt;/code&gt; 代表整个 Promise 链已经完全被解析了。 我们的 &lt;code&gt;getSomeJson()&lt;/code&gt; 例子能够通过使用 &lt;code&gt;done()&lt;/code&gt; 方法变得更加健壮了。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
getSomeJson().done(function(json) {  
  // when this throws, it won&#39;t be swallowed
  var obj = JSON.parse(json);
  console.log(obj);
});

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;&lt;code&gt;done()&lt;/code&gt; 也有一个 错误回调函数参数， &lt;code&gt;done(callback, errback)&lt;/code&gt;，就像 &lt;code&gt;then()&lt;/code&gt;一样。 因为整个 Promise 链已经完全解析了， 你就能够保证不会有任何突发的错误发生了。&lt;/p&gt;

&lt;h2 id=&#34;promise-resolution-needs-to-be-async:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;Promise Resolution Needs to be Async&lt;/h2&gt;

&lt;p&gt;在这篇文章的开始部分，我们通过 &lt;code&gt;setTimeout&lt;/code&gt; 耍了点小手段。 一旦我们修补那个 hack， 我们就不需要使用 setTimeout 了。 但是根据 &lt;code&gt;Promise/A+&lt;/code&gt; 规范的要求，Promise 的解析一定是异步的。 满足这个要求非常简单， 我们只需要简单的在 &lt;code&gt;handle()&lt;/code&gt; 的内部实现中包裹在 setTimeout 调用之内。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
function handle(handler) {  
  if(state === &#39;pending&#39;) {
    deferred = handler;
    return;
  }
  setTimeout(function() {
    // ... as before
  }, 1);
}

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;这就是全部所需要做的。 但实际上，真正的 Promise 库都不倾向于使用 setTimeout。 如果是一个面向 NodeJS 的库它很可能会使用 &lt;code&gt;process.nextTick&lt;/code&gt;， 面向浏览器的可能会使用新的 &lt;code&gt;setImmediate&lt;/code&gt; 或者一个 &lt;code&gt;setImmediate shim&lt;/code&gt;（目前为止只有 IE 支持 setImmediate）,又或者一个异步库如 Kris Kowal 的 &lt;code&gt;assp&lt;/code&gt;（Kris Kowal 也写看 Q， 一个流行的 Promise 库）。&lt;/p&gt;

&lt;h2 id=&#34;why-is-this-asyn-requirement-in-the-spec:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;Why Is This Asyn REquirement in the Spec&lt;/h2&gt;

&lt;p&gt;因为它能保证了执行控制流的一致性和可靠性。 考虑下面的认为的例子&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-javascript&#34;&gt;
var promise = doAnOperation();  
invokeSomething();  
promise.then(wrapItAllUp);  
invokeSomethingElse();  

&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;这里的调用流（call flow, 执行顺序？）是什么呢？ 根据命名，你可能会认为是 &lt;code&gt;invokeSomething()&lt;/code&gt; -&amp;gt; &lt;code&gt;invokeSomethingElse()&lt;/code&gt; -&amp;gt; &lt;code&gt;wrapItAllUp()&lt;/code&gt;。 但是这完全取决于 promise 的 resolve 是同步还是异步的。 如果 &lt;code&gt;doAnOperation()&lt;/code&gt; 是异步的工作方式， 那么就是上述的执行顺序。 但是如果它是同步工作的，那么执行顺序将是 &lt;code&gt;invokeSomething()&lt;/code&gt; -&amp;gt; &lt;code&gt;wrapItAllUp()&lt;/code&gt; -&amp;gt; &lt;code&gt;invokeSomethingElse()&lt;/code&gt;，这就非常不好了。&lt;/p&gt;

&lt;p&gt;为了避开这一点， Promise 总是异步的解析，即使有时候他们不是必须那么做。 这样做减少了不可预料的情况出现，让人们使用 Promise 的时候不需要考虑是同步还是异步的。&lt;/p&gt;

&lt;p&gt;Promise 总是要求至少在事件循环的下一个迭代中做解析。 但这不是一般标准函数回调函数的规定。&lt;/p&gt;

&lt;h2 id=&#34;before-we-wrap-up-then-promise:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;Before We Wrap Up &amp;hellip; then/promise&lt;/h2&gt;

&lt;p&gt;在外边有很多全特性支持的 Promise 库实现。 &lt;code&gt;then 组织&lt;/code&gt; 的 promise 库采用一个较简单的实习那方式，就是说它只实现了规范要求的，一点也不多。 如果你去看看它的实现的话，你会觉得非常的熟悉。 &lt;code&gt;then/promise&lt;/code&gt; 是这篇文章的代码的基础， 我们几乎实现了相同的 Promise。 感谢 Nathan Zadoks 和 Forbes Lindsay 提供的好用的库与在 Javascript Promise 上的工作。 Forbes Lindsay 也是一个在 promise.org 网站后的工作人员。&lt;/p&gt;

&lt;p&gt;这篇文章里的实现跟真正的 Promise 的实现还有一些不同。 因为还有更多的在 &lt;code&gt;Promise/A+&lt;/code&gt; 规定的细节我没有去处理。 我建议去阅读这个规范， 它文章篇幅短，而且内容简明。&lt;/p&gt;

&lt;h2 id=&#34;conclusion:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;Conclusion&lt;/h2&gt;

&lt;p&gt;如果你能够到达这里，非常感谢你的时间阅读！ 我们已经覆盖了 Promises 的核心了， 也是规范唯一规定的东西。 大部分实现都会提供一些额外的功能，如 &lt;code&gt;all()&lt;/code&gt;， &lt;code&gt;spread()&lt;/code&gt;，&lt;code&gt;race()&lt;/code&gt;，&lt;code&gt;denodeify()&lt;/code&gt; 等。 我建议浏览 &lt;code&gt;API docs for Bluebird&lt;/code&gt; 来看看 Promise 更多的可能。&lt;/p&gt;

&lt;p&gt;一旦我开始明白 Promise 的工作机制和 caveats，我开始真的喜欢他们了。 他们给我的工程带来了非常简洁和优雅的代码。 还有很多可以说的，这篇文章只是开始。&lt;/p&gt;

&lt;p&gt;如果你喜欢这篇文章， 你可以去　Twitter 上订阅我，看看我啥时候又写了像这样的指导文章。&lt;/p&gt;

&lt;h2 id=&#34;further-reading:bd840da09a6d51a9bdf28dd22f839db5&#34;&gt;Further Reading&lt;/h2&gt;
</description>
        </item>
      
    

  </channel>
</rss>
